global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'storeofcoins-api'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:5174']

  - job_name: 'users-api'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:5180']


